### ISSUE TITLE
Bug Preventing AutoReel and AutoMash from functioning

### ISSUE THREAD

**Issue by SoapyPuppy** [x8c8r/Webfishing#1]
Simply said autoreel and automash are not functioning in game. Autocast works fine however changing the configuration of the other two options brings no change and still requires user input. Client is in 2560x1440p fullscreen if that has any effect.

**Comment by Alaunae** [comment]
Do make sure that tacklebox is installed, and that when you launch the game, on the MODS menu, you do configure the mod (again), to make autoreel and smash enabled back again.

Had the same issue, and it fixed it.

**Comment by x8c8r** [comment]
This was most likely a result of Fishing+ 1.4.0 which had patience lure activated by default

**Comment by SoapyPuppy** [comment]
> 

Thanks, this fixed my issues :D
